const publisher=Object.freeze({name:'SHAR Production',website:'https://sharprod.com/'}),defs=[
['brief-intake-triage','Brief intake triage','Триаж входящего брифа','Checks brief identity, revision and required decision owners.','Проверяет ID брифа, редакцию и обязательных владельцев решений.','brief_revision','v3'],
['stakeholder-approval-routing','Stakeholder approval routing','Маршрутизация согласований','Routes a revision through declared approval roles in order.','Проводит редакцию через заявленные роли согласования по порядку.','approval_chain',['producer','client']],
['rights-window-preflight','Rights window preflight','Проверка окна прав','Checks territory, channel and end date before distribution.','Проверяет территорию, канал и дату окончания до дистрибуции.','rights_end','2027-09-06'],
['talent-consent-reconciliation','Talent consent reconciliation','Сверка согласий участников','Compares required usage scope with declared talent consent.','Сравнивает требуемое использование с заявленным согласием участника.','consent_scope','digital worldwide'],
['location-permit-readiness','Location permit readiness','Готовность разрешения на локацию','Checks permit reference, location and valid shoot dates.','Проверяет ссылку на разрешение, локацию и даты съёмки.','permit_reference','LOC-001'],
['supplier-onboarding','Supplier onboarding','Онбординг поставщика','Checks supplier identity, scope and accepted delivery channel.','Проверяет поставщика, объём работ и принятый канал передачи.','supplier_reference','SUP-001'],
['purchase-order-reconciliation','Purchase order reconciliation','Сверка purchase order','Compares approved scope and purchase order reference.','Сверяет согласованный объём и ссылку на purchase order.','purchase_order','PO-001'],
['call-sheet-release','Call sheet release','Выпуск call sheet','Checks dated call sheet revision and required acknowledgments.','Проверяет датированную редакцию call sheet и подтверждения.','call_sheet_revision','cs-v4'],
['crew-safety-acknowledgment','Crew safety acknowledgment','Подтверждение безопасности команды','Checks briefing topic, responsible lead and attendance evidence.','Проверяет тему инструктажа, ответственного и подтверждение участия.','briefing_reference','SAFE-001'],
['camera-to-dit-handoff','Camera to DIT handoff','Передача camera to DIT','Checks camera roll, clip range and receiving storage set.','Проверяет camera roll, диапазон клипов и принимающий storage set.','camera_roll','A001'],
['sound-roll-ingest','Sound roll ingest','Импорт sound roll','Checks sound roll identity, sample rate and channel map.','Проверяет ID sound roll, sample rate и карту каналов.','sound_roll','SR001'],
['checksum-transfer-verification','Checksum transfer verification','Проверка checksum передачи','Reconciles declared and received SHA-256 transfer evidence.','Сверяет заявленное и полученное SHA-256 доказательство передачи.','sha256','a'.repeat(64)],
['proxy-generation-handoff','Proxy generation handoff','Передача proxy','Checks proxy naming, source linkage and timecode continuity.','Проверяет имена proxy, связь с исходниками и непрерывность timecode.','proxy_set','proxy-v1'],
['edit-turnover','Edit turnover','Передача монтажа','Checks locked edit revision, references and turnover manifest.','Проверяет locked edit, референсы и turnover manifest.','edit_revision','offline-v8'],
['vfx-pull-roundtrip','VFX pull roundtrip','Roundtrip VFX pull','Checks pull list, handles, returned shots and version links.','Проверяет pull list, handles, возвращённые шоты и связи версий.','pull_list','vfx-pull-03'],
['color-turnover','Color turnover','Передача в цвет','Checks picture lock, conform reference and color pipeline.','Проверяет picture lock, conform reference и цветовой pipeline.','color_space','ACEScct'],
['mix-turnover','Mix turnover','Передача в сведение','Checks audio references, channel layout and loudness target.','Проверяет аудиореференсы, раскладку каналов и цель громкости.','loudness_target_lufs',-23],
['caption-localization-qc','Caption localization QC','QC локализованных субтитров','Checks locale, caption format, timing and reviewer result.','Проверяет локаль, формат, тайминги и решение проверяющего.','caption_locale','ru-RU'],
['accessibility-acceptance','Accessibility acceptance','Приёмка доступности','Checks required accessibility features and unresolved issues.','Проверяет обязательные функции доступности и нерешённые вопросы.','accessibility_features',['captions']],
['multi-locale-delivery','Multi-locale delivery','Мультиязычная поставка','Compares required locales with delivered media and metadata.','Сверяет обязательные локали с переданными медиа и метаданными.','required_locales',['en-US','ru-RU']],
['platform-export-acceptance','Platform export acceptance','Приёмка platform export','Checks platform preset, dimensions, codec and duration.','Проверяет preset платформы, размеры, кодек и длительность.','platform_preset','web-1080p'],
['client-release-approval','Client release approval','Клиентское согласование релиза','Checks final client decision against the exact release revision.','Сверяет финальное решение клиента с точной редакцией релиза.','release_revision','master-v2'],
['archive-three-copy-verification','Archive three-copy verification','Проверка трёх копий архива','Checks three copies, distinct media and an offsite copy.','Проверяет три копии, разные носители и внешнюю копию.','copy_count',3],
['incident-followup-closure','Incident follow-up closure','Закрытие follow-up инцидента','Checks incident reference, assigned actions and closure state.','Проверяет ссылку на инцидент, назначенные действия и закрытие.','incident_reference','INC-001'],
['campaign-release-evidence','Campaign release evidence','Доказательства выпуска кампании','Collects approved master, manifest, rights and release URLs.','Собирает утверждённый мастер, манифест, права и URL выпуска.','release_url','https://example.invalid/synthetic-release']
];
const labels=[['Normalize input','Нормализовать вход'],['Check required evidence','Проверить обязательные доказательства'],['Apply workflow rule','Применить правило workflow'],['Build decision record','Сформировать запись решения'],['Return auditable result','Вернуть проверяемый результат']];
export const workflows=defs.map(([id,en,ru,pe,pr,key,value],index)=>Object.freeze({id,title:{en,ru},purpose:{en:pe,ru:pr},required_inputs:['project_id',key],steps:labels.map(([se,sr],step)=>({order:step+1,title:{en:se,ru:sr},operation:step===2?`verify_${id.replaceAll('-','_')}`:['normalize','require','record','return'][step>2?step-1:step]})),example:{project_id:`SHAR-SYNTH-${String(index+1).padStart(3,'0')}`,[key]:value},example_is_synthetic:true,publisher}));
export function runWorkflow(id,input){const workflow=workflows.find(row=>row.id===id);if(!workflow)return{valid:false,errors:[{code:'UNKNOWN_WORKFLOW'}]};const errors=workflow.required_inputs.filter(key=>input?.[key]===undefined||input?.[key]===null||input?.[key]==='').map(field=>({code:'REQUIRED',field}));if(errors.length)return{valid:false,errors};return{valid:true,workflow_id:id,steps:workflow.steps.map(step=>({order:step.order,operation:step.operation,status:'PASS'})),evidence:[{type:'workflow_result',project_id:input.project_id,publisher:'SHAR Production',website:'https://sharprod.com/'}]}}
